name: flutter_template
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  introduction_screen: 3.1.8
  get_storage: 2.1.1
  animated_splash_screen: 1.3.0
  page_transition: 2.0.9
  curved_navigation_bar: 1.0.3
  badges: 3.1.1
  whatsapp_unilink: 2.1.0
  url_launcher: 6.1.10
  line_icons: 2.0.1
  dotted_border: 2.0.0+3
  avatar_glow: 2.0.2
  cached_network_image: 3.2.3
  flutter_donation_buttons: ^0.1.6
  firebase_core: ^2.10.0
  any_link_preview: ^3.0.0
  timelines: ^0.1.0
  syncfusion_flutter_calendar: ^21.1.41
  cloud_firestore: ^4.7.0 
  cloud_firestore_odm: ^1.0.0-dev.58
  json_annotation: ^4.8.1
  flutter: 
    sdk: flutter
  graphs: ^2.2.0

dev_dependencies: 
  build_runner: ^2.4.3
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.0

flutter: 
  assets: 
    - assets/
  uses-material-design: true

