// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaFd03HKiFXbyr1Y4cjA5ea6rQ7b8y3xI',
    appId: '1:822924365245:web:abf38bc6e1bc01a25cd6d4',
    messagingSenderId: '822924365245',
    projectId: 'ai-news-7b04b',
    authDomain: 'ai-news-7b04b.firebaseapp.com',
    storageBucket: 'ai-news-7b04b.appspot.com',
    measurementId: 'G-K7XJ5M64QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjCxLrPEqg_nLP3a8LEggdhJxU-rpVjTE',
    appId: '1:822924365245:android:a527a8545f228fa75cd6d4',
    messagingSenderId: '822924365245',
    projectId: 'ai-news-7b04b',
    storageBucket: 'ai-news-7b04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2kXCKL-dEcbcY2TWjIM7uitSgz8umubw',
    appId: '1:822924365245:ios:4035a988252bea565cd6d4',
    messagingSenderId: '822924365245',
    projectId: 'ai-news-7b04b',
    storageBucket: 'ai-news-7b04b.appspot.com',
    iosClientId: '822924365245-s8e32cphpjq6mu9nf2uvihok30bh3gt6.apps.googleusercontent.com',
    iosBundleId: 'com.aiuda.aiNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2kXCKL-dEcbcY2TWjIM7uitSgz8umubw',
    appId: '1:822924365245:ios:4035a988252bea565cd6d4',
    messagingSenderId: '822924365245',
    projectId: 'ai-news-7b04b',
    storageBucket: 'ai-news-7b04b.appspot.com',
    iosClientId: '822924365245-s8e32cphpjq6mu9nf2uvihok30bh3gt6.apps.googleusercontent.com',
    iosBundleId: 'com.aiuda.aiNews',
  );
}
